apiVersion: batch/v1
kind: Job
metadata:
  name: db-init-job
spec:
  template:
    spec:
      containers:
      - name: db-init
        image: postgres:16
        command:
          - sh
          - -c
          - |
            until pg_isready -h ibankmesa-pg-service -p 5432; do
              sleep 2
            done

            psql -h ibankmesa-pg-service -p 5432 \
                 -U apdbinst -d psqlmesadb \
                 -f /sql/wmfomf_v1.sql

        env:
        - name: PGPASSWORD
          value: Test@12345

        volumeMounts:
        - name: init-sql
          mountPath: /sql

      restartPolicy: Never

      volumes:
      - name: init-sql
        hostPath:
          path: /data/postgres-init
