apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-restore-job
  namespace: default
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never

      containers:
        - name: restore
          image: postgres:16

          env:
            - name: PGPASSWORD
              value: Test@12345

          command:
            - sh
            - -c
            - >
              set -e;

              echo "===== WAITING FOR POSTGRES SERVICE =====";

              until pg_isready -h df-db-omf-sit-service -p 5401 -U db_app_admin; do
                echo "Waiting for DB...";
                sleep 5;
              done;

              echo "===== DB READY =====";

              echo "===== CHECKING BACKUP FILE =====";

              if [ ! -f /tmp/backup_omf.sql ]; then
                echo "ERROR: backup file not found at /tmp/backup_omf.sql";
                exit 1;
              fi;

              ls -l /tmp/backup_omf.sql;

              echo "===== CREATING DATABASE IF NOT EXISTS =====";

              psql -h df-db-omf-sit-service -p 5401 -U db_app_admin -d postgres \
                -tc "SELECT 1 FROM pg_database WHERE datname='omfsitdb'" | grep -q 1 \
                || psql -h df-db-omf-sit-service -p 5401 -U db_app_admin -d postgres \
                -c "CREATE DATABASE omfsitdb";

              echo "===== STARTING RESTORE USING pg_restore =====";

              pg_restore \
                -h df-db-omf-sit-service \
                -p 5401 \
                -U db_app_admin \
                -d omfsitdb \
                --no-owner \
                --no-privileges \
                --verbose \
                /tmp/backup_omf.sql;

              echo "===== RESTORE COMPLETED SUCCESSFULLY =====";

          volumeMounts:
            - name: host-backup
              mountPath: /tmp

      volumes:
        - name: host-backup
          hostPath:
            path: /tmp
            type: Directory
