apiVersion: apps/v1
kind: Deployment
metadata:
  name: df-db-omf
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: df-db-omf
  template:
    metadata:
      labels:
        app: df-db-omf
    spec:
      containers:
        - name: postgres
          image: cache.artifactory.global.standardchartered.com/postgres:16

          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_DB
              value: omfdevdb
            - name: POSTGRES_USER
              value: db_app_admin
            - name: POSTGRES_PASSWORD
              value: Test@12345

          volumeMounts:
            # ✅ Persistent storage
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data

            # ✅ Init SQL script
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d

          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"

      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: pgdata-pvc

        - name: init-sql
          configMap:
            name: postgres-init-sql
