#!/bin/bash

echo "Waiting for MQ Queue Manager..."

for i in {1..60}
do
    dspmq | grep "QMNAME(HKIBK1S1).*Running"

    if [ $? -eq 0 ]; then
        echo "Queue Manager is running"
        break
    fi

    echo "Waiting..."
    sleep 5
done

if [ ! -f /mnt/mqm/.mq-config-restored ]; then

   echo "Applying MQSC restore..."

   runmqsc HKIBK1S1 < /etc/mqm-config/aeibk1s1-mq-config.mqsc \
   > /mnt/mqm/restore.log 2>&1

   touch /mnt/mqm/.mq-config-restored

   echo "MQSC restore completed"

else

   echo "MQSC already restored"

fi

tail -f /mnt/mqm/restore.log

kubectl create configmap mq-restore-script \
--from-file=restore-mq.sh \
-n ibank-mq

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mbnk-dev-mq
  namespace: ibank-mq

spec:
  replicas: 1

  selector:
    matchLabels:
      app: mbnk-dev-mq

  template:
    metadata:
      labels:
        app: mbnk-dev-mq

    spec:

      containers:

      - name: ibm-mq

        image: icr.io/ibm-messaging/mq:latest
        imagePullPolicy: IfNotPresent

        env:

        - name: LICENSE
          value: "accept"

        - name: MQ_QMGR_NAME
          value: "HKIBK1S1"

        ports:

        - containerPort: 1414
          name: mq

        - containerPort: 9443
          name: web

        volumeMounts:

        - name: mq-data
          mountPath: /mnt/mqm

        - name: mq-config
          mountPath: /etc/mqm-config

        - name: mq-restore-script
          mountPath: /usr/local/bin/restore-mq.sh
          subPath: restore-mq.sh

        command:
        - /bin/bash
        - -c
        - |
            chmod +x /usr/local/bin/restore-mq.sh

            /usr/local/bin/runmqserver &

            /usr/local/bin/restore-mq.sh

      volumes:

      - name: mq-data
        persistentVolumeClaim:
          claimName: mq-pvc

      - name: mq-config
        configMap:
          name: mq-config

      - name: mq-restore-script
        configMap:
          name: mq-restore-script
