apiVersion: apps/v1
kind: Deployment
metadata:
  name: df-db-sit-omf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: df-db-sit-omf
  template:
    metadata:
      labels:
        app: df-db-sit-omf
    spec:
      containers:
        - name: postgres
          image: postgres:16

          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_DB
              value: omfsitdb
            - name: POSTGRES_USER
              value: db_app_admin
            - name: POSTGRES_PASSWORD
              value: Test@12345
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata

          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data

            - name: host-backup
              mountPath: /tmp

          #################################
          # 🔥 FIXED RESTORE LOGIC
          #################################
          lifecycle:
            postStart:
              exec:
                command:
                  - sh
                  - -c
                  - |
                    echo "===== WAITING FOR POSTGRES ====="

                    until pg_isready -h localhost -U $POSTGRES_USER; do
                      echo "Waiting for DB..."
                      sleep 3
                    done

                    echo "===== DB READY ====="

                    if [ -f /tmp/backup_omf.sql ]; then
                      echo "Backup file found"

                      if [ -f /var/lib/postgresql/data/pgdata/.restore_done ]; then
                        echo "Restore already done. Skipping."
                        exit 0
                      fi

                      echo "===== STARTING RESTORE ====="

                      PGPASSWORD=$POSTGRES_PASSWORD psql \
                        -h localhost \
                        -U $POSTGRES_USER \
                        -d $POSTGRES_DB \
                        -f /tmp/backup_omf.sql

                      echo "===== RESTORE COMPLETED ====="

                      touch /var/lib/postgresql/data/pgdata/.restore_done
                    else
                      echo "Backup file NOT found in /tmp"
                    fi

      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: pgdata-omfsit-pvc

        - name: host-backup
          hostPath:
            path: /tmp
            type: Directory
