apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgdata-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/pgdata
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgdata-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: df-db-omf
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: df-db-omf
  template:
    metadata:
      labels:
        app: df-db-omf
    spec:
      containers:
        - name: postgres
          image: cache.artifactory.global.standardchartered.com/postgres:16
          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_DB
              value: omfdevdb
            - name: POSTGRES_USER
              value: db_app_admin
            - name: POSTGRES_PASSWORD
              value: Test@12345

          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data   # ✅ VERY IMPORTANT

          livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 10
            periodSeconds: 10

          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"

      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: pgdata-pvc   # ✅ binding PVC
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: df-db-omf
  ports:
    - port: 5401
      targetPort: 5432
      nodePort: 30541
